Repository hatchways/team-old-fashioned, pull requests merged in 2021-08, with the labels that each got.

#90 Payments in #73
  client/src/components/PaymentForm/PaymentForm.tsx
  client/src/components/PaymentMethods/PaymentMethods.tsx
  client/src/components/PaymentMethods/useStyles.ts
  client/src/helpers/APICalls/setPaymentMethodConfirmed.ts
  client/src/interface/Payments.ts
  client/src/interface/User.ts
  client/src/mocks/mockUser.ts
  client/src/pages/ProfileSetting/PaymentDetails/PaymentDetails.tsx
  client/src/pages/ProfileSetting/ProfileSetting.tsx
  server/controllers/auth.js
  server/controllers/payment.js
  server/controllers/user.js
  server/models/User.js
  server/routes/payment.js
  server/routes/user.js
Labels: Integration

#104 Feature message notifications
  client/src/components/NavBar/NavBar.tsx
  client/src/components/NotifsMsgDropdown/NotifsMsgDropdown.tsx
  client/src/context/useNotificationsContext.tsx
  client/src/context/usePaymentsContext.tsx
  client/src/helpers/APICalls/notifications.ts
  client/src/interface/Notifications.ts
  client/src/interface/User.ts
  client/src/mocks/mockUser.ts
  client/src/pages/Message/Message.tsx
  client/src/pages/Notifications/Notifications.tsx
  client/src/pages/Notifications/NotificationsList/NotificationsList.tsx
  server/app.js
  server/controllers/notification.js
  server/models/Notification.js
  server/routes/notification.js
Labels: Fullstack

#106 Add payments gate for creating contests
  client/src/context/usePaymentsContext.tsx
  client/src/pages/Contest/NewContest.tsx
  client/src/pages/ContestPayment/ContestPayment.tsx
Labels: Integration

#107 Hotfix: Sort Notifications
  server/controllers/notification.js
  server/models/Notification.js
Labels: Backend
